### ISSUE TITLE
Update to RR 5.7.0 - needed to support Intel Sapphire Rapids

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/BugReporting.jl#140]
```
[FATAL src/PerfCounters_x86.h:118:compute_cpu_microarch()] Intel CPU type 0x806f0 unknown
```

Trying to trace a segfault in LLVM on 1.9.3 on a Sapphire Rapids CPU, but RR was failing because it didn't support the CPU.

Looks like just-released RR 5.7.0 includes this support:
https://github.com/rr-debugger/rr/blame/7cf5a12dba5aaeea9efc5ad97176b07b5614e350/src/PerfCounters_x86.h#L89-L90

**Comment by BioTurboNick** [comment]
cc: @maleadt, looks like you've been doing the most recent RR bumps on Yggdrasil? Is this an easy thing to do, or will it require some work? And if so, how can I help?

**Comment by maleadt** [comment]
https://github.com/JuliaLang/rr/commits/release-5.6 would have to be rebased on top of master. The problem is that some of Keno's patches don't apply cleanly anymore on top of 5.7/master. I have the bare minimum in https://github.com/JuliaLang/rr/commits/tb/master (the XRC0 patch is so that we can replay traces from other processors), but there's also
- https://github.com/rr-debugger/rr/pull/2529, which seems closed, so can we just drop that patch?
- https://github.com/JuliaLang/rr/commit/17e0471cbc1fd3d591576080714a3a94aff93e2c and https://github.com/JuliaLang/rr/commit/2fb2a96f76be9e3e7fa11b16cabd7f591f49c247, for which there aren't even PRs

Maybe @Keno can comment?

**Comment by BioTurboNick** [comment]
I think all that may be needed to support Sapphire Rapids is just this small PR: https://github.com/rr-debugger/rr/pull/3513

At least it seems to work on my machine.

**Comment by maleadt** [comment]
OK, I can backport that. I'll wait for @Keno to chime in on the above patchlist before attempting an update to 5.7.
